export const mydata = [
  { id: crypto.randomUUID() ,
    title: "milk",
    category: "grocery",
    amount: "30",
  },
  { id: crypto.randomUUID() ,
    title: "shirt",
    category: "cloths",
    amount: "300",
  },
  { id: crypto.randomUUID() ,
    title: "vegetable",
    category: "grocery",
    amount: "130",
  },
  { id: crypto.randomUUID() ,
    title: "Eletricity",
    category: "Bills",
    amount: "200",
  },
];
